---

- name: install epel-release on RedHat
  yum: name=epel-release state=present
  when: ansible_os_family == "RedHat"

- name: install  nginx on debian
  apt: name=nginx state=present
  when: ansible_os_family == "Debian"
 
- name: install nginx on RedHat
  yum: name=nginx state=present
  when: ansible_os_family == "RedHat"

- name: checks targget nginx.conf
  stat:
    path: /etc/nginx/nginx.conf
  register: stat_result

- name: mv if nginx conf exist in target
  shell: mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.org
  when: stat_result.stat.exists

- name: copy config file
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: start nginx

