---

- import_playbook: update_dist.yml

- hosts: {{ hosts }}
  remote_user: root
  roles:
#    - GitServer
    - nginx
    - csf
    - geerlingguy.nfs
    - ftp
    - samba
    - postfix
    - fail2ban
#   - apache2

- import_playbook: site.yml
- import_playbook: scan.yml
