---

- include: update_dist.yaml
- include: scan.yaml

- hosts: all
  become: yes
  tasks:
    - name: cp openvpn script to server but you should execute it manually ....
      template:
        src: openvpn-install.sh
        dest: /root/openvpn-install.sh
    - name: remove old openvpn
      yum: name=openvpn state=absent
      when: ansible_os_family == "RedHat"
    - name: remove old openvpn
      apt: name=openvpn state=absent
      when: ansible_os_family == "Debian"
    - name: remove openvpn default ovpn files
      shell: rm -f /root/*.ovpn
    - name: execute openvpn 
      shell: echo -ne "\n" | bash openvpn-install.sh 
  roles:
    - nginx
    - csf
    - geerlingguy.nfs
    - ftp
    - samba
    - postfix
    - fail2ban
