---

- hosts: ubuntu
  become: yes
  tasks:
    - name: install net-tools
      yum: name=net-tools state=latest
      when: ansible_os_family == "RedHat"

    - name: install pip3
      apt: name=python3-pip state=present 
      when: ansible_os_family == "Debian"
    - name: install pip3
      yum: name=python3-pip state=present
      when: ansible_os_family == "RedHat"
      ignore_errors: true

    - name: cp pip.sh to target machine
      template:
        src: pip.sh
        dest: /root/pip.sh  
    
    - name: install python dependencies
      shell: bash pip.sh

    - name: copy scanner.py
      template:
        src: scanner.py
        dest: /tmp/scanner.py

    - name: execute scanner.py
      shell: python3 /tmp/scanner.py -i enp0s3 && python3 /tmp/scanner.py -i public
      register: results

    - name: show results
      debug: msg={{ results.stdout_lines }}
