---

- hosts: all
  become: yes
  tasks:
    - name: install net-tools
      yum: name=net-tools state=latest
      when: ansible_os_family == "RedHat"

    - name: install pip3
      apt: name=python3-pip state=present 
      when: ansible_os_family == "Debian"
      ignore_errors: true

    
    - name: install pip3
      yum: name=python3-pip state=present
      when: ansible_os_family == "RedHat"
      ignore_errors: true

    - pip:
        name: sockets
        name: DateTime
        name: DateTime
        name: requests
        name: netifaces 
        executable: pip-3 

    - name: copy scanner.py
      copy:
        src: scanner.py
        dest: /tmp/scanner.py

    - name: execute scanner.py
      shell: python3 /tmp/scanner.py -i {{  interface }}  && python3 /tmp/scanner.py -i public
      register: results

    - name: show results
      debug: msg={{ results.stdout_lines }}
