---
- name: Install WordPress, MariaDB, Nginx, and PHP-FPM
  hosts: parham
  remote_user: root
  # remote_user: user
  # sudo: yes

  roles:
    - common
    - mariadb
    - nginx
    - php-fpm
    - wordpress
