---

- hosts: {{ hosts }}
  become: yes
  tasks:
    - name: update debian systems
      apt: upgrade=dist update_cache=yes
      when: ansible_os_family == "Debain"

    - name: update Redhat systems
      yum: name=* state=latest update_cache=yes
      when: ansible_os_family == "RedHat"
      
