---

- name: install postfix on Redhat (in debians need manually installation)
  yum: name=postfix,cyrus-sasl-plain,mailx state=latest 
  when: ansible_os_family == "RedHat"
  ignore_errors: true

- name: copy config file to targst machine
  template: 
    src: main.cf.j2
    dest: /etc/postfix/main.cf
  when: ansible_os_family == "RedHat"

- name: copy customize shell
  template:
    src: customize.sh.j2
    dest: /tmp/customize.sh
  when: ansible_os_family == "RedHat"

- name: execute customize script
  shell: bash /tmp/customize.sh
  notify: start postfix
  when: ansible_os_family == "RedHat"
