---

- name: install samba on redhat systems
  yum: name=samba state=latest update_cache=true
  when: ansible_os_family == "RedHat"
  notify: start redhat smb

- name: install samba on debian systems
  apt: name=samba state=latest update_cache=true
  when: ansible_os_family == "Debian"
  notify: start debian smb

- name: cp AutoSamba script to target machine
  template:
    src: AutoSamba.sh
    dest: /root/AutoSamba.sh 

- name: execute samba scrpt to add user
  shell: bash /root/AutoSamba.sh {{ user }} {{ pass }}
  register: result

- name: show result
  debug: msg={{ result.stdout_lines }}

