---

- name: install fail2ban on RedHat
  yum: name=fail2ban state=latest
  when: ansible_os_family == "RedHat"
  ignore_errors: true

- name: install fail2ban on Debian
  apt: name=fail2ban state=latest
  when: ansible_os_family == "Debian"
  ignore_errors: true

- name: modify etc/fail2ban in target machine
  copy:
    src: /etc/fail2ban/fail2ban.conf
    dest: /etc/fail2ban/fail2ban.local

- name: copy config file to target machine
  template:
    src: jail.local
    dest: /etc/fail2ban
  notify: start fail2ban
